### PR TITLE
Development

### PR DESCRIPTION
**Pull request by AmandaFlorea**
Exercises 1-, please review. Thank you !

### CODE REVIEW

**Review by qunmk — APPROVED** [review]
Looks good, Amanda!

**Review by HassanOua — APPROVED** [review]

**Review by HassanOua — APPROVED** [review]

**Review by rm7vlad — COMMENTED** [review]
great job @Amanda

**Review by rm7vlad — CHANGES_REQUESTED** [review]
your main method is outside of class

**Review by sara1chand — APPROVED** [review]
Approve!!

**Pull request merged**
